[project]
name = "comfyui-magicdance"
description = "ComfyUI supports over [a/Boese0601/MagicDance](https://github.com/Boese0601/MagicDance)."
version = "1.0.0"
license = {file = "LICENSE"}
dependencies = ["absl-py", "aiohttp", "aiosignal", "antlr4-python3-runtime", "async-timeout", "attrs", "beautifulsoup4", "cachetools", "clip", "cmake", "cycler", "decord", "diffusers", "einops", "einops-exts", "entmax", "filelock", "fonttools", "frozenlist", "fsspec", "ftfy", "gdown", "google-auth", "google-auth-oauthlib", "grpcio", "huggingface-hub", "imageio", "imageio-ffmpeg", "importlib-metadata", "kiwisolver", "kornia", "langdetect", "lightning-utilities", "lit", "markdown", "markupsafe", "matplotlib", "multidict", "mypy-extensions", "networkx", "ninja", "oauthlib", "omegaconf", "open-clip-torch", "opencv-python", "packaging", "ply", "protobuf", "pyasn1", "pyasn1-modules", "pyparsing", "pyre-extensions", "python-dateutil", "pytorch-lightning", "pywavelets", "pyyaml", "regex", "requests-oauthlib", "rotary-embedding-torch", "rsa", "safetensors", "scikit-image", "scipy", "sentencepiece", "six", "soupsieve", "tensorboard", "tensorboard-data-server", "tensorboard-plugin-wit", "thriftpy2", "tifffile", "timm", "tokenizers", "torchdiffeq", "torchmetrics", "tqdm", "transformers", "triton", "typing-inspect", "wcwidth", "werkzeug", "xformers", "yarl", "zipp"]

[project.urls]
Repository = "https://github.com/bombax-xiaoice/ComfyUI-MagicDance"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = ""
DisplayName = "ComfyUI-MagicDance"
Icon = ""
